language: java
jdk:
  - oraclejdk17
dist: trusty
# git strips the wrapper jar file so we have to force its download during the build
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test